# LogistiX – Enterprise Supply Chain Intelligence Platform

## Notebook 04 — Feature Engineering

### Phase

Feature Engineering

### Objective

The objective of this notebook is to create business-focused analytical features from the cleaned supply chain dataset. These engineered features will enhance business reporting, KPI calculation, SQL analysis, dashboard development, and executive decision-making.

---

### Workflow

1. Import Libraries
2. Load Cleaned Dataset
3. Create Business Features
4. Validate Engineered Features
5. Export Feature Engineered Dataset

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("LogistiX - Feature Engineering Started")

LogistiX - Feature Engineering Started

In [2]:
file_path = "../data/processed/cleaned_supply_chain_dataset.csv"

df = pd.read_csv(file_path)

print(df.shape)

(180519, 53)

In [3]:
df.head()

       type  days_for_shipping_real  days_for_shipment_scheduled  benefit_per_order  sales_per_customer   delivery_status  late_delivery_risk  category_id   category_name customer_city customer_country customer_email customer_fname  customer_id customer_lname customer_password customer_segment customer_state           customer_street  customer_zipcode  department_id department_name   latitude   longitude        market  order_city order_country  order_customer_id order_date_dateorders  order_id  order_item_cardprod_id  order_item_discount  order_item_discount_rate  order_item_id  order_item_product_price  order_item_profit_ratio  order_item_quantity   sales  order_item_total  order_profit_per_order    order_region      order_state     order_status  order_zipcode  product_card_id  product_category_id  product_description                                product_image product_name  product_price  product_status shipping_date_dateorders   shipping_mode
0     DEBIT                       3                            4          91.250000          314.640015  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Cally        20755       Holloway         XXXXXXXXX         Consumer             PR  5365 Noble Nectar Island             725.0              2         Fitness  18.251453  -66.037056  Pacific Asia      Bekasi     Indonesia              20755   2018-01-31 22:56:00     77202                    1360            13.110000                      0.04         180517                    327.75                     0.29                    1  327.75        314.640015               91.250000  Southeast Asia  Java Occidental         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0      2018-02-03 22:56:00  Standard Class
1  TRANSFER                       5                            4        -249.089996          311.359985     Late delivery                   1           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Irene        19492           Luna         XXXXXXXXX         Consumer             PR          2679 Rustic Loop             725.0              2         Fitness  18.279451  -66.037064  Pacific Asia     Bikaner         India              19492   2018-01-13 12:27:00     75939                    1360            16.389999                      0.05         179254                    327.75                    -0.80                    1  327.75        311.359985             -249.089996      South Asia         Rajastán          PENDING            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0      2018-01-18 12:27:00  Standard Class
2      CASH                       4                            4        -247.779999          309.720001  Shipping on time                   0           73  Sporting Goods      San Jose          EE. UU.      XXXXXXXXX        Gillian        19491      Maldonado         XXXXXXXXX         Consumer             CA      8510 Round Bear Gate           95125.0              2         Fitness  37.292233 -121.881279  Pacific Asia     Bikaner         India              19491   2018-01-13 12:06:00     75938                    1360            18.030001                      0.06         179253                    327.75                    -0.80                    1  327.75        309.720001             -247.779999      South Asia         Rajastán           CLOSED            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0      2018-01-17 12:06:00  Standard Class
3     DEBIT                       3                            4          22.860001          304.809998  Advance shipping                   0           73  Sporting Goods   Los Angeles          EE. UU.      XXXXXXXXX           Tana        19490           Tate         XXXXXXXXX      Home Office             CA           3200 Amber Bend           90027.0              2         Fitness  34.125946 -118.291016  Pacific Asia  Townsville     Australia              19490   2018-01-13 11:45:00     75937                    1360            22.940001                      0.07         179252                    327.75                     0.08                    1  327.75        304.809998               22.860001         Oceania       Queensland         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0      2018-01-16 11:45:00  Standard Class
4   PAYMENT                       2                            4         134.210007          298.250000  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX           Orli        19489      Hendricks         XXXXXXXXX        Corporate             PR  8671 Iron Anchor Corners             725.0              2         Fitness  18.253769  -66.037048  Pacific Asia  Townsville     Australia              19489   2018-01-13 11:24:00     75936                    1360            29.500000                      0.09         179251                    327.75                     0.45                    1  327.75        298.250000              134.210007         Oceania       Queensland  PENDING_PAYMENT            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0      2018-01-15 11:24:00  Standard Class

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   type                         180519 non-null  object
 1   days_for_shipping_real       180519 non-null  int64
 2   days_for_shipment_scheduled  180519 non-null  int64
 3   benefit_per_order            180519 non-null  float64
 4   sales_per_customer           180519 non-null  float64
 5   delivery_status              180519 non-null  object
 6   late_delivery_risk           180519 non-null  int64
 7   category_id                  180519 non-null  int64
 8   category_name                180519 non-null  object
 9   customer_city                180519 non-null  object
 10  customer_country             180519 non-null  object
 11  customer_email               180519 non-null  object
 12  customer_fname               180519 non-null  object
 13  customer_id                  180519 non-null  int64
 14  customer_lname               180511 non-null  object
 15  customer_password            180519 non-null  object
 16  customer_segment             180519 non-null  object
 17  customer_state               180519 non-null  object
 18  customer_street              180519 non-null  object
 19  customer_zipcode             180516 non-null  float64
 20  department_id                180519 non-null  int64
 21  department_name              180519 non-null  object
 22  latitude                     180519 non-null  float64
 23  longitude                    180519 non-null  float64
 24  market                       180519 non-null  object
 25  order_city                   180519 non-null  object
 26  order_country                180519 non-null  object
 27  order_customer_id            180519 non-null  int64
 28  order_date_dateorders        180519 non-null  object
 29  order_id                     180519 non-null  int64
 30  order_item_cardprod_id       180519 non-null  int64
 31  order_item_discount          180519 non-null  float64
 32  order_item_discount_rate     180519 non-null  float64
 33  order_item_id                180519 non-null  int64
 34  order_item_product_price     180519 non-null  float64
 35  order_item_profit_ratio      180519 non-null  float64
 36  order_item_quantity          180519 non-null  int64
 37  sales                        180519 non-null  float64
 38  order_item_total             180519 non-null  float64
 39  order_profit_per_order       180519 non-null  float64
 40  order_region                 180519 non-null  object
 41  order_state                  180519 non-null  object
 42  order_status                 180519 non-null  object
 43  order_zipcode                24840 non-null   float64
 44  product_card_id              180519 non-null  int64
 45  product_category_id          180519 non-null  int64
 46  product_description          0 non-null       float64
 47  product_image                180519 non-null  object
 48  product_name                 180519 non-null  object
 49  product_price                180519 non-null  float64
 50  product_status               180519 non-null  int64
 51  shipping_date_dateorders     180519 non-null  object
 52  shipping_mode                180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [5]:
df.columns.tolist()

['type',
 'days_for_shipping_real',
 'days_for_shipment_scheduled',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_id',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_email',
 'customer_fname',
 'customer_id',
 'customer_lname',
 'customer_password',
 'customer_segment',
 'customer_state',
 'customer_street',
 'customer_zipcode',
 'department_id',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_customer_id',
 'order_date_dateorders',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'order_zipcode',
 'product_card_id',
 'product_category_id',
 'product_description',
 'product_image',
 'product_name',
 'product_price',
 'product_status',
 'shipping_date_dateorders',
 'shipping_mode']

In [6]:
feature_df = df.copy()

# Business Feature Engineering

The following section creates business-driven analytical features that improve supply chain performance analysis, executive reporting, KPI calculation, and dashboard insights.

In [7]:
df.columns.tolist()

['type',
 'days_for_shipping_real',
 'days_for_shipment_scheduled',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_id',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_email',
 'customer_fname',
 'customer_id',
 'customer_lname',
 'customer_password',
 'customer_segment',
 'customer_state',
 'customer_street',
 'customer_zipcode',
 'department_id',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_customer_id',
 'order_date_dateorders',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'order_zipcode',
 'product_card_id',
 'product_category_id',
 'product_description',
 'product_image',
 'product_name',
 'product_price',
 'product_status',
 'shipping_date_dateorders',
 'shipping_mode']

In [8]:
feature_df["order_date_dateorders"] = pd.to_datetime(
    feature_df["order_date_dateorders"]
)

feature_df["shipping_date_dateorders"] = pd.to_datetime(
    feature_df["shipping_date_dateorders"]
)

In [9]:
feature_df["shipping_lead_time"] = (
    feature_df["shipping_date_dateorders"]
    - feature_df["order_date_dateorders"]
).dt.days

In [10]:
feature_df["delivery_delay"] = (
    feature_df["days_for_shipping_real"]
    - feature_df["days_for_shipment_scheduled"]
)

In [11]:
feature_df["on_time_delivery"] = np.where(
    feature_df["delivery_delay"] <= 0,
    "On Time",
    "Delayed"
)

In [12]:
feature_df["profit_margin"] = (
    feature_df["order_profit_per_order"]
    / feature_df["sales"]
) * 100

In [13]:
feature_df["order_value_category"] = pd.qcut(
    feature_df["sales"],
    q=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Premium"
    ]
)

In [14]:
feature_df["customer_type"] = np.where(
    feature_df["customer_segment"] == "Consumer",
    "B2C",
    "B2B"
)

In [15]:
feature_df["high_value_order"] = np.where(
    feature_df["sales"] >= feature_df["sales"].median(),
    1,
    0
)

In [16]:
feature_df["weekend_order"] = np.where(
    feature_df["order_date_dateorders"].dt.dayofweek >= 5,
    1,
    0
)

In [17]:
feature_df["order_month"] = (
    feature_df["order_date_dateorders"]
    .dt.month_name()
)

In [18]:
feature_df["order_year"] = (
    feature_df["order_date_dateorders"]
    .dt.year
)

In [19]:
feature_df["shipping_speed"] = pd.cut(
    feature_df["days_for_shipping_real"],
    bins=[0,2,5,20],
    labels=[
        "Fast",
        "Standard",
        "Slow"
    ]
)

In [20]:
feature_df["profit_category"] = np.where(
    feature_df["order_profit_per_order"] >= 0,
    "Profit",
    "Loss"
)

In [21]:
feature_df["discount_category"] = pd.cut(
    feature_df["order_item_discount_rate"],
    bins=[-0.01,0,0.10,0.25,1],
    labels=[
        "No Discount",
        "Low",
        "Medium",
        "High"
    ]
)

In [22]:
feature_df["quantity_category"] = pd.cut(
    feature_df["order_item_quantity"],
    bins=[0,1,3,5,100],
    labels=[
        "Single",
        "Small",
        "Medium",
        "Bulk"
    ]
)

In [23]:
feature_df.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_email,customer_fname,customer_id,customer_lname,customer_password,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,market,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,order_zipcode,product_card_id,product_category_id,product_description,product_image,product_name,product_price,product_status,shipping_date_dateorders,shipping_mode,shipping_lead_time,delivery_delay,on_time_delivery,profit_margin,order_value_category,customer_type,high_value_order,weekend_order,order_month,order_year,shipping_speed,profit_category,discount_category,quantity_category
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class,3,-1,On Time,27.841342,Premium,B2C,1,0,January,2018,Standard,Profit,Low,Single
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class,5,1,Delayed,-75.999999,Premium,B2C,1,1,January,2018,Standard,Loss,Low,Single
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class,4,0,On Time,-75.600305,Premium,B2C,1,1,January,2018,Standard,Loss,Low,Single
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class,3,-1,On Time,6.974829,Premium,B2B,1,1,January,2018,Standard,Profit,Low,Single
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class,2,-2,On Time,40.948896,Premium,B2B,1,1,January,2018,Fast,Profit,Low,Single

In [24]:
new_features = [
    "shipping_lead_time",
    "delivery_delay",
    "on_time_delivery",
    "profit_margin",
    "order_value_category",
    "customer_type",
    "high_value_order",
    "weekend_order",
    "order_month",
    "order_year",
    "shipping_speed",
    "profit_category",
    "discount_category",
    "quantity_category"
]

feature_df[new_features].head()

   shipping_lead_time  delivery_delay on_time_delivery  profit_margin order_value_category customer_type  high_value_order  weekend_order order_month  order_year shipping_speed profit_category discount_category quantity_category
0                   3              -1          On Time      27.841342              Premium           B2C                 1              0     January        2018       Standard          Profit               Low            Single
1                   5               1          Delayed     -75.999999              Premium           B2C                 1              1     January        2018       Standard            Loss               Low            Single
2                   4               0          On Time     -75.600305              Premium           B2C                 1              1     January        2018       Standard            Loss               Low            Single
3                   3              -1          On Time       6.974829              Premium           B2B                 1              1     January        2018       Standard          Profit               Low            Single
4                   2              -2          On Time      40.948896              Premium           B2B                 1              1     January        2018           Fast          Profit               Low            Single

In [25]:
feature_df.to_csv(
    "../data/processed/feature_engineered_supply_chain_dataset.csv",
    index=False
)

In [26]:
print("Feature engineering completed successfully.")

Feature engineering completed successfully.

# Feature Engineering Summary

## Business Features Created

- Shipping Lead Time
- Delivery Delay
- On-Time Delivery Flag
- Profit Margin
- Order Value Category
- Customer Type
- High Value Order Flag
- Weekend Order Flag
- Order Month
- Order Year
- Shipping Speed Category
- Profit Category
- Discount Category
- Quantity Category

## Outcome

The engineered dataset is now enriched with business-oriented features and is ready for exploratory data analysis, SQL analytics, KPI reporting, and interactive dashboard development.